//
// Copyright (c) The Holo Core Contributors
//
// SPDX-License-Identifier: MIT
//

pub mod configuration;
pub mod notification;
pub mod rpc;
pub mod state;
pub mod yang;

use holo_northbound as northbound;

use crate::instance::Instance;
use crate::version::{Ospfv2, Ospfv3, Version};

pub trait NorthboundVersion<V: Version> {
    type ListEntry<'a>: northbound::state::ListEntryKind;

    const YANG_OPS_STATE: northbound::state::YangOps<Instance<V>>;
    const YANG_OPS_RPC: northbound::rpc::YangOps<Instance<V>>;
}

// Autogenerated code from YANG modules.
#[allow(unused_imports, unused_variables)]
#[allow(clippy::module_inception)]
pub mod yang_gen {
    use holo_utils::crypto::CryptoAlgo;
    use holo_utils::ip::AddressFamily;
    use holo_utils::southbound::OspfRouteType;
    use holo_utils::sr::IgpAlgoType;
    pub use routing::control_plane_protocols::control_plane_protocol::ospf;

    use crate::area::AreaType;
    use crate::gr::GrExitReason;
    use crate::interface::{InterfaceType, ism};
    use crate::lsdb::LsaLogReason;
    use crate::neighbor::nsm;
    use crate::northbound::configuration::{InstanceTraceOption, InterfaceTraceOption};
    use crate::northbound::yang::FletcherChecksum16;
    use crate::packet::iana::PacketType;
    use crate::packet::tlv::GrReason;
    use crate::spf::{self, SpfLogType};
    include!(concat!(env!("OUT_DIR"), "/yang_objects.rs"));
    pub mod ops {
        use super::*;
        pub mod ospfv2 {
            use crate::instance::Instance;
            use crate::version::Ospfv2;
            type Provider = Instance<Ospfv2>;
            include!(concat!(env!("OUT_DIR"), "/yang_ops_ospfv2.rs"));
        }
        pub mod ospfv3 {
            use crate::instance::Instance;
            use crate::version::Ospfv3;
            type Provider = Instance<Ospfv3>;
            include!(concat!(env!("OUT_DIR"), "/yang_ops_ospfv3.rs"));
        }
    }
    pub mod config {
        use super::*;
        include!(concat!(env!("OUT_DIR"), "/yang_config.rs"));
    }
}

// ===== impl Ospfv2 =====

impl NorthboundVersion<Self> for Ospfv2 {
    type ListEntry<'a> = yang_gen::ops::ospfv2::ListEntry<'a>;

    const YANG_OPS_STATE: northbound::state::YangOps<Instance<Self>> = yang_gen::ops::ospfv2::YANG_OPS_STATE;
    const YANG_OPS_RPC: northbound::rpc::YangOps<Instance<Self>> = yang_gen::ops::ospfv2::YANG_OPS_RPC;
}

// ===== impl Ospfv3 =====

impl NorthboundVersion<Self> for Ospfv3 {
    type ListEntry<'a> = yang_gen::ops::ospfv3::ListEntry<'a>;

    const YANG_OPS_STATE: northbound::state::YangOps<Instance<Self>> = yang_gen::ops::ospfv3::YANG_OPS_STATE;
    const YANG_OPS_RPC: northbound::rpc::YangOps<Instance<Self>> = yang_gen::ops::ospfv3::YANG_OPS_RPC;
}
