//
// Copyright (c) The Holo Core Contributors
//
// SPDX-License-Identifier: MIT
//

pub mod configuration;
pub mod rpc;
pub mod state;
pub mod yang;

use holo_northbound as northbound;

use crate::instance::Instance;
use crate::version::{Ripng, Ripv2, Version};

// RIP version-specific code.
pub trait NorthboundVersion<V: Version> {
    type ListEntry<'a>: northbound::state::ListEntryKind;

    const YANG_OPS_STATE: northbound::state::YangOps<Instance<V>>;
    const YANG_OPS_RPC: northbound::rpc::YangOps<Instance<V>>;
}

// Autogenerated code from YANG modules.
#[allow(unused_imports, unused_variables)]
#[allow(clippy::module_inception)]
pub mod yang_gen {
    use holo_utils::crypto::CryptoAlgo;
    pub use routing::control_plane_protocols::control_plane_protocol::rip;

    use crate::interface::SplitHorizon;
    use crate::northbound::configuration::TraceOption;
    use crate::route::RouteType;

    include!(concat!(env!("OUT_DIR"), "/yang_objects.rs"));
    pub mod ops {
        use super::*;
        pub mod ripv2 {
            use crate::instance::Instance;
            use crate::version::Ripv2;
            type Provider = Instance<Ripv2>;
            include!(concat!(env!("OUT_DIR"), "/yang_ops_ripv2.rs"));
        }
        pub mod ripng {
            use crate::instance::Instance;
            use crate::version::Ripng;
            type Provider = Instance<Ripng>;
            include!(concat!(env!("OUT_DIR"), "/yang_ops_ripng.rs"));
        }
    }
    pub mod config {
        use super::*;
        include!(concat!(env!("OUT_DIR"), "/yang_config.rs"));
    }
}

// ===== impl Ripv2 =====

impl NorthboundVersion<Self> for Ripv2 {
    type ListEntry<'a> = yang_gen::ops::ripv2::ListEntry<'a>;

    const YANG_OPS_STATE: northbound::state::YangOps<Instance<Self>> = yang_gen::ops::ripv2::YANG_OPS_STATE;
    const YANG_OPS_RPC: northbound::rpc::YangOps<Instance<Self>> = yang_gen::ops::ripv2::YANG_OPS_RPC;
}

// ===== impl Ripng =====

impl NorthboundVersion<Self> for Ripng {
    type ListEntry<'a> = yang_gen::ops::ripng::ListEntry<'a>;

    const YANG_OPS_STATE: northbound::state::YangOps<Instance<Self>> = yang_gen::ops::ripng::YANG_OPS_STATE;
    const YANG_OPS_RPC: northbound::rpc::YangOps<Instance<Self>> = yang_gen::ops::ripng::YANG_OPS_RPC;
}
